<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ahmets-MacBook-Pro.local" ignored="0" name="LoginTest" tests="3" failures="1" timestamp="21 Dec 2017 12:38:31 GMT" time="19.392" errors="0">
  <testcase name="invalidLoginTest_InvalidUserNameInvalidPassword" time="6.379" classname="tests.LoginTests"/>
  <testcase name="invalidLoginTest_EmptyUserEmptyPassword" time="3.721" classname="tests.LoginTests">
    <skipped/>
  </testcase> <!-- invalidLoginTest_EmptyUserEmptyPassword -->
  <testcase name="invalidLoginTest_EmptyUserEmptyPassword" time="4.337" classname="tests.LoginTests">
    <failure type="java.lang.AssertionError" message="expected [WRONG MESSAGE FOR FAILURE!] but found [Bu alan覺n doldurulmas覺 zorunludur.]">
      <![CDATA[java.lang.AssertionError: expected [WRONG MESSAGE FOR FAILURE!] but found [Bu alan覺n doldurulmas覺 zorunludur.]
	at pages.LoginPage.verifyLoginPassword_aroundBody4(LoginPage.java:43)
	at pages.LoginPage$AjcClosure5.run(LoginPage.java:1)
	at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
	at pages.LoginPage.verifyLoginPassword(LoginPage.java:43)
	at tests.LoginTests.invalidLoginTest_EmptyUserEmptyPassword(LoginTests.java:73)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- invalidLoginTest_EmptyUserEmptyPassword -->
</testsuite> <!-- LoginTest -->
